org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=1.20.1

forge_version=47.4.13
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

ftb_quests_version=2001.4.17

mod_id=curvyquests
mod_name=Curvy Quests
mod_license=MIT license
mod_version=1.0.1
mod_group_id=com.igrock888.curvyquests
mod_authors=igrock888
mod_description=An addon for FTB Quests mod that adds dependency curves